version: 2
updates:
  # Root Gradle build (uses libs.versions.toml as version catalog)
  - package-ecosystem: "gradle"
    directory: "/" # Root project
    schedule:
      interval: "weekly"

  # App module
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "weekly"

  # Sandbox UI module
  - package-ecosystem: "gradle"
    directory: "/sandbox-ui"
    schedule:
      interval: "weekly"

  # Python AI backend
  - package-ecosystem: "pip"
    directory: "/ai_backend"
    schedule:
      interval: "weekly"

  # Node.js/JavaScript (generated resources)
  - package-ecosystem: "npm"
    directory: "/generated"
    schedule:
      interval: "weekly"
