[versions]
accompanistPager = "0.36.0"
accompanistSystemuicontroller = "0.36.0"
agp = "8.14.2"  
animationTooling = "1.9.8"   # <-- fixed missing quote
toolchainsFoojayResolver = "1.0.0"
converterGson = "3.0.0"
datastoreCore = "1.1.7"
firebaseConfigKtx = "22.1.2"
firebaseStorageKtx = "21.0.2"
hiltCompilerVersion = "1.2.0"
hiltWork = "1.2.0"
kotlin = "2.2.0"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesPlayServices = "1.10.2"
ksp = "2.2.0-1.0.24"
composeBom = "2025.06.01"
composeCompiler = "2.2.0"
firebaseBom = "33.16.0"
hilt = "2.56.2"
hiltAndroid = "2.56.2"
lifecycleCommonJava8 = "2.9.1"
lifecycleExtensions = "2.2.0"
lifecycleProcess = "2.9.1"
lifecycleRuntimeCompose = "2.9.1"
lifecycleService = "2.9.1"
lifecycleViewmodelCompose = "2.9.1"
material3 = "1.3.2"
openapiGenerator = "7.6.0"
googleServices = "4.4.3"
firebaseCrashlytics = "3.0.4"
firebasePerf = "1.4.2"
coreKtx = "1.16.0"
appcompat = "1.7.1"
lifecycle = "2.9.1"
activityCompose = "1.10.1"
navigation = "2.9.0"
room = "2.7.2"
workManager = "2.10.2"
datastore = "1.1.7"
securityCrypto = "1.1.0-beta01"
hiltNavigationCompose = "1.2.0"
junit = "4.13.2"
kotlinxCoroutinesTest = "1.10.2"
mockk = "1.13.10"
androidxTestExtJunit = "1.2.1"
espressoCore = "3.6.1"
coilCompose = "2.7.0"
accompanistPermissions = "0.37.3"
retrofit = "3.0.0"
okhttp = "4.12.0"
retrofitKotlinxSerializationConverter = "1.0.0"
kotlinxSerializationJson = "1.9.0"
kotlinxDatetime = "0.7.0"
guava = "33.4.8-android"
timber = "5.0.1"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
openapiGenerator = { id = "org.openapi.generator", version.ref = "openapiGenerator" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebasePerf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composeCompiler" }
orgGradleToolchainsFoojayResolver = { id = "org.gradle.toolchains.foojay-resolver", version.ref = "toolchainsFoojayResolver" }

# [libraries] section unchanged, just ensure all version.refs point to valid [versions] keys
