name: Build AuraFrameFX (Kotlin KSP2)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/temurin-24-jdk-amd64
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '24'

    - name: Download Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 35
        ndk-version: 25.2.9519653

    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Upload build outputs (APK)
      uses: actions/upload-artifact@v4
      with:
        name: aura-apk
        path: app/build/outputs/apk/debug/*.apk
