name: Build AuraFrameFX (Kotlin KSP2)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /opt/android-sdk # JAVA_HOME was already removed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24  # Changed name
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24' # Changed to JDK 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: 26.2.11394342

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: aura-apk
          path: app/build/outputs/apk/debug/*.apk
